"""update contact column

Revision ID: 125966decdac
Revises: 
Create Date: 2026-04-20 13:25:42.681129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125966decdac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
